name: Wyoming Satellite Local
version: "1.0.5"
slug: wyoming_satellite_local
description: Wyoming Satellite mit Audio-Zugriff für Assist-Pipeline
arch:
  - aarch64
  - amd64
  - armv7
audio: true
homeassistant_api: true
url: https://github.com/rhasspy/wyoming-satellite
startup: system
boot: auto
ports:
  10700/tcp: 10700
options:
  name: "ha_pi_sat"
  uri: "tcp://0.0.0.0:10700"
  mic_device: "alsa_input.usb-Generalplus_IMI_2500_microphone-00.mono-fallback"
  snd_device: "alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo"
  wake_uri: ""
  wake_word: ""
  debug: false
schema:
  name: str
  uri: str
  mic_device: str
  snd_device: str
  wake_uri: str?
  wake_word: str?
  debug: bool
